# Azure Batch and Azure Storage account credentials
credentials:
  batch:
    account_key: <account_key>
    account_service_url: <account_service_url>
  storage:
    mystorageaccount:
      account: <storage_account_name>
      account_key: <account_key>
      endpoint: core.windows.net