# computing resource needed for executing the jobs found in jobs.yaml
pool_specification:
  id: experiment2
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
  vm_size: standard_ds5_v2 # azure VM size
  vm_count:
    dedicated: 90 # number of nodes
    low_priority: 0 
  max_tasks_per_node: 1 # maximum number of containers that can do stuff per task