# specify the jobs to execute

# containers are removed upon exit
# pool is removed upon all jobs are completed
job_specifications:
- id: random_forest
  auto_complete: true # set job complete once all tasks are complete
  tasks:
  - docker_image: hilde/experiment_1:sleep
    additional_docker_run_options:
    - -w /exp # force working directory to be /exp of docker container
    - --shm-size 2g # set shm size larger than standard 64m to prevent joblib from hanging
    task_factory: # give task list
      parametric_sweep:
        permutations:
          iterable:
          - '3'
          - '6'
          - '11'
          - '12'
          - '14'
          - '15'
          - '16'
          - '18'
          - '22'
          - '23'
          - '28'
          - '29'
          - '31'
          - '32'
          - '37'
          - '41'
          - '43'
          - '45'
          - '49'
          - '53'
          - '58'
          - '219'
          - '2074'
          - '2079'
          - '3021'
          - '3022'
          - '3481'
          - '3560'
          - '3573'
          - '3902'
          - '3903'
          - '3904'
          - '3913'
          - '3917'
          - '3918'
          - '3954'
          - '7592'
          - '9910'
          - '9946'
          - '9950'
          - '9952'
          - '9954'
          - '9955'
          - '9956'
          - '9957'
          - '9960'
          - '9964'
          - '9971'
          - '9976'
          - '9977'
          - '9978'
          - '9981'
          - '9985'
          - '10093'
          - '10101'
          - '14952'
          - '14954'
          - '14965'
          - '14969'
          - '14970'
          - '52950'
          - '125920'
          - '125922'
          - '125966'
          - '146195'
          - '146197'
          - '146227'
          - '146800'
          - '146802'
          - '146817'
          - '146818'
          - '146819'
          - '146820'
          - '146821'
          - '146822'
          - '146824'
          - '146825'
          - '167119'
          - '167120'
          - '167121'
          - '167124'
          - '167125'
          length: 1
    command: --task_id {0} --num 1000 --classifier random_forest --log False --openml_apikey <openml_apikey> 
    remove_container_after_exit: true